-- Add sample clients data for testing
INSERT INTO public.clients (
  id,
  company_name,
  contact_person,
  phone,
  address,
  city,
  po_box,
  email,
  payment_method,
  security_rate,
  installation_rate,
  current_job_rate,
  notes,
  status,
  created_by_id,
  created_by,
  is_sample
) VALUES 
(
  gen_random_uuid(),
  'חברת אבטחה מקצועית בע"מ',
  'יוסי כהן',
  '050-1234567',
  'רחוב הרצל 15',
  'תל אביב',
  '61000',
  'yossi@security-pro.co.il',
  'monthly',
  350.00,
  280.00,
  320.00,
  'לקוח VIP - זמינות 24/7',
  'active',
  (SELECT id FROM auth.users WHERE email = 'root@vazana.com' LIMIT 1),
  'root@vazana.com',
  true
),
(
  gen_random_uuid(),
  'מרכז קניות גרנד קניון',
  'שרה לוי',
  '03-9876543',
  'שדרות ירושלים 45',
  'פתח תקווה',
  '49000',
  'sarah@grandcanyon.co.il',
  'weekly',
  300.00,
  250.00,
  275.00,
  'שירותי אבטחה למרכז קניות גדול',
  'active',
  (SELECT id FROM auth.users WHERE email = 'root@vazana.com' LIMIT 1),
  'root@vazana.com',
  true
);
